# Generated by Django 3.1.7 on 2021-03-21 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumeapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
