# Generated by Django 3.1.7 on 2021-04-02 17:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('resumeapp', '0003_auto_20210321_2122'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='is_approved',
            field=models.BooleanField(default=False, verbose_name='Проверено'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='Опубликовано'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
