# Generated by Django 3.1.7 on 2021-04-02 17:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resumeapp', '0004_auto_20210402_1712'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vacancyapp', '0004_auto_20210402_1712'),
        ('mainapp', '0002_auto_20210321_2141'),
    ]

    operations = [
        migrations.CreateModel(
            name='Responses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активность')),
                ('resume', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='resumeapp.resume', verbose_name='Резюме')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Кто откликнулся')),
                ('vacancy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vacancyapp.vacancy', verbose_name='Вакансия')),
            ],
        ),
        migrations.AddConstraint(
            model_name='responses',
            constraint=models.UniqueConstraint(fields=('vacancy', 'user'), name='unique_vacancy_user'),
        ),
        migrations.AddConstraint(
            model_name='responses',
            constraint=models.UniqueConstraint(fields=('resume', 'user'), name='unique_resume_user'),
        ),
    ]
