# Generated by Django 3.1.7 on 2021-03-21 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancyapp', '0002_vacancy_is_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='is_approved',
            field=models.BooleanField(default=False, verbose_name='Проверено'),
        ),
    ]
