# Generated by Django 3.1.7 on 2021-04-02 17:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('vacancyapp', '0003_auto_20210321_2122'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vacancy',
            options={'ordering': ('-created_at',), 'verbose_name': 'Вакансия', 'verbose_name_plural': 'Вакансии'},
        ),
        migrations.RemoveField(
            model_name='vacancy',
            name='created',
        ),
        migrations.RemoveField(
            model_name='vacancy',
            name='draft',
        ),
        migrations.RemoveField(
            model_name='vacancy',
            name='name',
        ),
        migrations.RemoveField(
            model_name='vacancy',
            name='updated',
        ),
        migrations.AddField(
            model_name='vacancy',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Создана'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vacancy',
            name='is_draft',
            field=models.BooleanField(default=False, verbose_name='Черновик'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='salary',
            field=models.FloatField(blank=True, default=0, verbose_name='Заработная плата'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Обновлена'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='vacancy_name',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Наименование должности'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='description',
            field=models.TextField(blank=True, max_length=250, null=True, verbose_name='Описание должности'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='Опубликовано'),
        ),
    ]
