# Generated by Django 3.1.7 on 2021-04-02 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='about',
            new_name='user_about',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='age',
            new_name='user_age',
        ),
        migrations.RemoveField(
            model_name='user',
            name='description',
        ),
        migrations.RemoveField(
            model_name='user',
            name='main_business',
        ),
        migrations.AddField(
            model_name='user',
            name='company_about',
            field=models.TextField(blank=True, null=True, verbose_name='О компании'),
        ),
        migrations.AddField(
            model_name='user',
            name='company_main_business',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Род деятельности'),
        ),
        migrations.AddField(
            model_name='user',
            name='company_since',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Основана'),
        ),
        migrations.AddField(
            model_name='user',
            name='file',
            field=models.FileField(blank=True, upload_to='avatars', verbose_name='Фото'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_partner',
            field=models.BooleanField(blank=True, default=False, verbose_name='Партнер'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_patronymic',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Отчество'),
        ),
        migrations.AlterField(
            model_name='user',
            name='company_name',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Название компании'),
        ),
    ]
