# Generated by Django 3.1.7 on 2021-03-07 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='about',
            field=models.TextField(null=True, verbose_name='О себе'),
        ),
        migrations.AlterField(
            model_name='user',
            name='description',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
    ]
