# Generated by Django 3.1.7 on 2021-03-11 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='cellphone',
            field=models.PositiveBigIntegerField(verbose_name='номер телефона'),
        ),
    ]
